---
platform: "linux"
image_resource:
  type: "docker-image"
  source:
    repository: "dpb587/automata"
    tag: "bosh"
inputs:
  - name: "repository"
  - name: "stemcell"
outputs:
  - name: "repository"
    path: "repository-output"
run:
  path: "repository/automata/tasks/rally/write-stemcell/execute.sh"
params:
  config: ~ # required
  commit_prefix: ~
  git_committer_email: "ci@localhost"
  git_committer_name: "CI"
