---
platform: "linux"
image_resource:
  type: "docker-image"
  source:
    repository: "dpb587/automata"
    tag: "bosh"
inputs:
  - name: "manifest"
  - name: "repository"
outputs:
  - name: "repository"
    path: "repository-output"
run:
  path: "repository/ci/automata/tasks/bosh/create-env/execute.sh"
params:
  manifest: ~ # required
  state: ~ # required
  ssh_key: ~ # required
  git_committer_email: "ci@localhost"
  git_committer_name: "CI"
